### ISSUE TITLE
On re-merging forks

### ISSUE THREAD

**Issue by icefoxen** [app-dirs-rs/app_dirs2#1]
I talked with a few people about what to do if @AndyBarron ever returns and wants to continue development of `app_dirs`. The conclusion seemed to be we should choose one crate or the other to "win" and make that the active crate, while the other one can depend on and re-export the appropriate version of the "winner" so that it can be deprecated but continues working and gets bug fixes automatically.

Seems like a reasonable solution to me. Anyone see any holes in it?

**Comment by kornelski** [comment]
I wish crates.io had a better support for merging/forking...

Now that the next version of app_dirs is published, you can add it as your dependency, and re-export it:

```toml
app_dirs = "1.2"
```

```rust
extern create app_dirs;
pub use app_dirs::*;
```

This way programs with both app_dirs2 + app_dirs won't have duplicate code.

**Comment by kornelski** [comment]
Looks like revival of app_dirs was for just one release, and the crate is still unmaintained.
