### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by VZout** [app-dirs-rs/app_dirs2#3]
Android support is currently missing, Shouldn't be to hard to add this.

**Comment by VZout** [comment]
Can't assign myself but I'll create a PR soon.

**Comment by kornelski** [comment]
Yes, that would be welcome!

**Comment by icefoxen** [comment]
Yes, that would be nice!  Thanks a lot.  (Even if I mostly use the `directories` crate these days...  XD)
